# Define the blocks that players are allowed to break here #
# The format is <block_name: timeout>                      #
# Make sure to type the block name in all lowercase        #

blocks:
  iron_ore: 35
  coal_ore: 30
  gold_ore: 45
  redstone_ore: 50
  emerald_ore: 60
  lapis_ore: 50
  diamond_ore: 90
  log: 0

allowOpBreak: true